81 auth guard
PDG-NUTRI/PDG_APP pull request #84
Opened 2022-08-30 15:10 UTC by LucaCoduriV

2022-08-30 17:12 UTC, chloefont requested changes
Juste une toute petite modif

2022-08-30 17:12 UTC, chloefont commented on lib/router/auth_gard.dart
>    var isAuthenticated = false;
Tu peux l'enlever

2022-08-30 19:59 UTC, LucaCoduriV commented on lib/router/auth_gard.dart
>    var isAuthenticated = false;
c'est fait !

2022-08-31 06:52 UTC, chloefont approved these changes
Yess parfait

2022-08-31 06:52 UTC, merged